<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>MonkeModManager</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.IO.Compression.FileSystem">
      <HintPath>../../../../opt/dotnet/shared/Microsoft.NETCore.App/8.0.31/System.IO.Compression.FileSystem.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../../opt/dotnet/shared/Microsoft.NETCore.App/8.0.31/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>